export const translations ={
en :{
    "t1":"CITY",
    "t2":"PARTNER",
    "t3":"ABOUT US",
    "t4":"GOKIDO TOOL",
    "t5":"CONTACT",
    "t6":"Delivery or Takeaway Food",
    "t7":"All restaurants",
    "t8":"with unique food",
    "t9":"at the best price",
    "t10":"Search",
    "t11":"with nice location",
    "t12":"Your Address or postal code",
    "t13":"Trending",
    "t14":"Sushi",
    "t15":"Burgher",
    "t16":"Chinese",
    "t17":"Pizza",
    "t18":"Popular Categories",
    "t19":"Japanese",
    "t20":"Vegiterian",
    "t21":"Bakery",
    "t22":"Mexican",
    "t23":"Choose from the most popular restaurants in your neighborhood.",
    "t24":"Order, enjoy and support your local heroes!.",
    "t25":"GokidoGo Delivery",
    "t26":"We Deliver to your Office",
    "t27":"Enjoy a tasty food in minutes!",
    "t28":"Start Now!",
    "t29":"You Order Your Favourite Food",
    "t30":"Here you can find all the restaurants in your zone.",
    "t31":"Restaurants Packs In Re-Usable Bowls",
    "t32":"We have more than 1000 menus online.",
    "t33":"You Eat Out Of The Bowls",
    "t34":"It's quick, easy and totally secure.",
    "t35":"This is how Go Kidogo works!",
    "t36":"It's very easy to order the food with minimal contact delivery.",
    "t37":"Order more!!",
    "t38":"To reduce waste...lets order more responsibly",
    "t39":"You Borrow Re-Usable Bowls",
    "t40":"Have it delivered or picked up conveniently.",
    "t41":"QUICK LINKS",
    "t42":"That's how it works",
    "t43":"Imprint",
    "t44":"Conditions",
    "t45":"Privacy",
    "t46":"Cookie",
    "t47":"To Register",
    "t48":"Categories",
    "t49":"Top Categories",
    "t50":"Best Rated",
    "t51":"Best Price",
    "t52":"Latest Submissions",
    "t53":"Secure Payment Methods",
    "t54":"Terms and conditions",
    "t55":"restaurants in total",
    "t56":"Address, neighborhood...",
    "t57":"Search",
    "t58":"Change address",
    "t59":"All",
    "t60":"Delivery",
    "t61":"Pickup",
    "t62":"Free Delivery for your first 14 days!",
    "t63":"Contact Us",
    "t64":"Connect with us",
    "t65":"Customer and restaurant support",
    "t66":"Address",
    "t67":"Contact",
    "t68":"Name",
    "t69":"Email",
    "t70":"Telephone",
    "t71":"Message",
    "t72":"Submit",
    "t73":"Order Summary",
    "t74":"TOTAL",
    "t75":"Pickup",
    "t76":"Checkout now",
    "t77":"Preorder",
    "t78":"Available Soon",
    "t79":"cart",
    "t80":"Date",
    "t81":"Hour",
    "t82":"Type",
    "t83":"Order Confirmed!",
    "t84":"No Order Detail Found!",
    "t85":"Something went wrong",
    "t86":"Please enter Order No",
    "t87":"Order ID",
    "t88":"FOLLOW US",
    "t89":"Social Media",
    "t90":"View All",
    "t91":"Search",
    "t92":"You Return The Reusable Bowls",
    "t93":"Restaurants Cleans Reusable Bowls",
    "t94":"Nudeln",
    "t95":"Indisch",
    "t96":"Thai uvm",
    "t97":"Select from 1000+ healthy menu items and have it ordered in our zero-waste boxes.",
    "t98":"Address",
    "t100":"Nudeln",
    "t101":"Curry",
    "t102":"Vegan",
    "t103":"Halal",
    "t104":"Contact Us",
    "t105":"Connect with us",
    "t106":"Drop Us a Line",
    "t107":"Message",
    "t108":"Submit",
    "t109":"Email",
    "t110":"About Us",
    "t111":"Contact",
    "t112":"Cart",
    "t113":"Order Overview",
    "t114":"Order Summary",
    "t115":"Delivery",
    "t116":"Pickup",
    "t117":"Date",
    "t118":"Hour",
    "t119":"Type",
    "t120":"EMail ID",
    "t121":"Order Now",
    "t122":"Delivery charge",
    "t123":"free over",
    "t124":"Add ingredients",
    "t125":"Total",
    "t126":"Order Confirmed!",
    "t127":"Order ID",
    "t128":"No Order Detail Found!",
    "t129":"Something went wrong",
    "t130":"Please enter Order No",
    "t131":"Support",
    "t132":"Username",
    "t133":"Password",
    "t134":"Remember me",
    "t135":"Forgot Password?",
    "t136":"Don’t have an account?",
    "t137":"Sign up",
    "t138":"Please confirm login email below",
    "t139":"You will receive an email containing a link allowing you to reset your password to a new preferred one.",
    "t140":"My Profile",
    "t141":"Dashboard",
    "t142":"Orders",
    "t143":"Address",
    "t144":"Order No",
    "t145":"Date",
    "t146":"Status",
    "t147":"Action",
    "t148":"The following addresses will be used on the checkout page by default.",
    "t149":"Billing Information",
    "t150":"Shipping address",
    "t151":"Reset Password!",
    "t152":"Email",
    "t153":"New Password",
    "t154":"Confirm Password",
    "t155":"Restaurants",
    "t156":"Takeaway",
    "t157":"Delivery",
    "t158":"Salutation",
    "t159":"Woman",
    "t160":"Mister",
    "t161":"First name",
    "t162":"Surname",
    "t163":"Telephone/Mobile No.",
    "t164":"Email ID",
    "t165":"Delivery",
    "t166":"Street (without house number)",
    "t167":"House no.",
    "t168":"House number",
    "t169":"Delivery notice",
    "t170":"Pick up day",
    "t171":"delivery time",
    "t172":"Tip",
    "t173":"packing material",
    "t174":"Reusable packaging (requires a deposit)/Reusable",
    "t175":"recycle/recycle",
    "t176":"Disposable packaging/reduce disposable packaging",
    "t177":"remark",
    "t178":"e.g. allergies, special wishes...",
    "t179":"Cutlery",
    "t180":"Order details",
    "t181":"Payment method",
    "t182":"cash payment",
    "t183":"EC numbers",
    "t184":"City",
    "t185":"Postal code",
    "t186":"floor",
    "t187":"Company name",
    "t188":"Pickup",
    "t189":"pick up time",
    "t190":"Legal",
    "t191":"FAQ"
},

de:{

"t1" : "Stadt",
"t2" : "Unsere Partner",
"t3" : "Über uns",
"t4" : "Partner*in werden",
"t5" : "Kontakt",
"t6" : "Fair Essen bestellen ohne Verpackungsmüll!",
"t7" : "Restaurants mit einzigartigem Essen",
"t8" : "Leckere Speisen zu fairen Preisen",
"t9" : "zu fairen Preisen",
"t10" : "Suchen",
"t11" : "Nachhaltig in eine einwegverpackungsfreie Zukunft",
"t12" : "Deine Anschrift oder die Postleitzahl",
"t13" : "Angesagte Lokale",
"t14" : "Sushi",
"t15" : "Burger",
"t16" : "Chinesisch",
"t17" : "Pizza",
"t18" : "Beliebte Kategorien",
"t19" : "Japanisch",
"t20" : "Vegetarisch",
"t21" : "Bäckerei",
"t22" : "Mexikanisch",
"t23" : "Wähle aus einem von vielen der beliebtesten Restaurants aus deiner Nachbarschaft.",
"t24" : "Bestelle, genieße und unterstütze lokale Restaurants.",
"t25" : "Go Kidogo Bestellplattform",
"t26" : "Unsere Partnerrestaurants liefern in dein Büro.",
"t27" : "Genieße dein leckeres Essen frei von Verpackungsmüll und zu fairen Preisen, für dich und deinen Lieblingsgastronomen.",
"t28" : "Starte jetzt!",
"t29" : "Finde nachhaltige Restaurants in deiner Nähe",
"t30" : "Hier findest du alle Restaurants in deinem Umkreis.",
"t31" : "Wähle aus mehr als 1.000 Speisen",
"t32" : "Wir haben mehr als 1000 leckere Menüs Online verfügbar.",
"t33" : "Zahle mit der Bezahlmethode deiner Wahl",
"t34" : "Der Bestellprozess ist schnell, sicher und bequem.",
"t35" : "Liefern oder Abholen?",
"t36" : "Es ist einfach und bequem Speisen über Go Kidogo Plattform zu bestellen.",
"t37" : "Verpackungsmülleinsparen und gemeinnützige Projekte fördern.",
"t38" : "Mit jeder Bestellung unterstützt  Go Kidogo Bildungsprojekte der PROBONO Schulpartnerschaften.",
"t39" : "Genieße deine wohlverdiente Mahlzeit",
"t40" : "Einfach und bequem liefern lassen oder selber abholen.",
"t41" : "Links",
"t42" : "So funktioniert´s",
"t43" : "Impressum",
"t44" : "Koditionen",
"t45" : "Privatsphäre",
"t46" : "Cookies",
"t47" : "Zur Anmeldung",
"t48" : "Kategorien",
"t49" : "Top Kategorien",
"t50" : "Best bewertesten Am Besten bewertet",
"t51" : "Super Preise",
"t52" : "Neuzugänge",
"t53" : "Sichere Zahlungsmethoden",
"t54" : "AGB's",
"t55" : "Restaurants an tollen Standorten",
"t56" : "Anschrift",
"t57" : "Suchen",
"t58" : "Anschrift ändern",
"t59" : "Alle",
"t60" : "Lieferung",
"t61" : "Selbstabholung",
"t62" : "Kostenlose Lieferung",
"t63" : "Kontaktiere uns",
"t64" : "Sprich mit uns",
"t65" : "Kunden und Restaurant Support",
"t66" : "Anschrift",
"t67" : "Kontakt",
"t68" : "Name",
"t69" : "E-mail",
"t70" : "Telefon",
"t71" : "Nachricht",
"t72" : "Absenden",
"t73" : "Bestellübersicht",
"t74" : "Total",
"t75" : "Abholung",
"t76" : "Checkout",
"t77" : "Vorbestellung",
"t78" : "Bad Verfügbar",
"t79" : "Warenkorb",
"t80" : "Datum",
"t81" : "Stunde",
"t82" : "Typ",
"t83" : "Bestellung wurde bestätigt!",
"t84" : "Keine Bestelldaten gefunden!",
"t85" :"Ups, etwas ist schief gelaufen!",
"t86" :"Bitte Bestellnummer eintragen",
"t87" :"Bestellnummer",
"t88" :"Folge uns!",
"t89" :"Soziale Medien",
"t90" :"alles Ansehen",
"t91" :"Suchen",
"t92" :"Gebe den Behälter spätestens nach 14 Tagen zurück",
"t93" :"Anschließend sorgen unsere Partnergastronomen für eine fachgerechte Reinigung der Behälter.",
"t94":"Nudeln",
"t95":"Indisch",
"t96":"Thai uvm",
"t97":"Wähle aus über 1.000 gesunden Speisen und lass sie dir in unseren Zero-Waste-Boxen liefern.",
"t98":"Anschrift",
"t100":"Nudeln",
"t101":"Curry",
"t102":"Vegan",
"t103":"Halal",
"t104":"Kontakt",
"t105":"Nutze unser Kontaktformular!",
"t106":"Kontaktiere Uns",
"t107":"Nachricht",
"t108":"Senden",
"t109":"E-Mail",
"t110":"Über uns",
"t111":"Kontakt",
"t112":"Warenkorb",
"t113":"Bestellübersicht",
"t114":"Bestellübersicht",
"t115":"Lieferung",
"t116":"Selbstabholung",
"t117":"Datum",
"t118":"Uhrzeit",
"t119":"Bestellart",
"t120":"E-Mail ID",
"t121":"Verbindlich Bestellen",
"t122":"Delivery charge",
"t123":"free over",
"t124":"Add ingredients",
"t125":"Total",
"t126":"Order Confirmed!",
"t127":"Order ID",
"t128":"No Order Detail Found!",
"t129":"Something went wrong",
"t130":"Please enter Order No",
"t131":"Support",
"t132":"Username",
"t133":"Password",
"t134":"Remember me",
"t135":"Forgot Password?",
"t136":"Don’t have an account?",
"t137":"Sign up",
"t138":"Please confirm login email below",
"t139":"You will receive an email containing a link allowing you to reset your password to a new preferred one.",
"t140":"My Profile",
"t141":"Dashboard",
"t142":"Orders",
"t143":"Address",
"t144":"Order No",
"t145":"Date",
"t146":"Status",
"t147":"Action",
"t148":"The following addresses will be used on the checkout page by default.",
"t149":"Billing Information",
"t150":"Shipping address",
"t151":"Reset Password!",
"t152":"Email",
"t153":"New Password",
"t154":"Confirm Password",
"t155":"Restaurants",
"t156":"Abholung",
"t157":"Lieferung",
"t158":"Anrede",
"t159":"Frau",
"t160":"Herr",
"t161":"Vorname",
"t162":"Name",
"t163":"Telefon/ Mobile Nr.",
"t164":"EMail ID",
"t165":"Lieferung",
"t166":"Strasse (ohne Haus Nr.)",
"t167":"Haus Nr.",
"t168":"hausnummer",
"t169":"Lieferhinweis",
"t170":"Abholtag",
"t171":"Lieferzeit",
"t172":"Trinkgeld",
"t173":"Verpackungsmaterial",
"t174":"Mehrwegverpackung (Pfandpflichtig)/Reusable",
"t175":"recyceln/Recycle",
"t176":"Einwegverpackung/Reduce Disposable Packaging",
"t177":"Bemerkung",
"t178":"z.B Allergien, Sonderwuüsche..",
"t179":"Besteck",
"t180":"Bestelldaten",
"t181":"Zahlungsart",
"t182":"Barzahlung",
"t183":"EC Zahlen",
"t184":"Stadt",
"t185":"Postleitzahl",
"t186":"Etage",
"t187":"Firmen Name",
"t188":"Abholung",
"t189":"Abholzeit",
"t190":"Legal",
"t191":"FAQ"
 },

 

};